#General
[general]
	#Activate the Update-Checker
	update-checker = true
	#Enables tooltips for some blocks/items in your inventory
	enable_tooltips = true
	#Enables some description for some blocks/items in JEI
	enable_descriptions = true
