[Materials]
	#This material will be used to reforge an item that does not have a material override or repair item
	Fallback = "minecraft:obsidian"
	#In this list you can define different reforge items for specific equipment.
	#This can override repair items and will be used instead of the fallback item in case no repair item exists.
	#The left item is the equipment and right is the material.
	Overrides = ["minecraft:bow,minecraft:string", "minecraft:crossbow,minecraft:iron_ingot"]

[Reforging]
	#A list of equipment that cannot be reforged.
	Blacklist = [" "]
	#If true, items have a chance to be automatically reforged when they enter the player's inventory.
	AutoReforge = true
	#The chance an item has of being automatically reforged.
	#Max is 1.0 (100%) and minimum is 0.1 (10%).
	AutoReforgeChance = 0.5
